# -*- coding: utf-8 -*-
"""oop 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EITeL5oFv8ropixcKAmdYJ5dsK0bhiuF
"""

class Atm:
  def __init__(self):
    self.pin = ""
    self.balance = 0
    self.menu()

  def menu(self):
    user_input = input("""
    Hello, how would you like to proceed?
    1. Enter 1 to create pin
    2. Enter 2 to change pin
    3. Enter 3 to check balance
    4. Enter 4 to withdraw
    5. Enter 5 to exit
    """)
    if user_input == "1":
       self.create_pin()
       self.menu()
    elif user_input=="2":
      self.change_pin()
      self.menu()
    elif user_input=="3":
      self.check_balance()
      self.menu()
    elif user_input=="4":
      self.withdraw()
    elif user_input=="5":
      exit()
    else:
      print("Invalid option")
      exit()

  def create_pin(self):
      user_pin=input("Enter your pin")
      self.pin = user_pin
      user_balance = int(input("Enter balance"))
      self.balance = user_balance
      print("Pin set successfully")
  # def change_pin(self):
  #   old_pin = input("Enter old pin")
  #   if old_pin == self.pin:
  #     new_pin = input("Enter new pin")
  #     self.pin = new_pin
  #     if new_pin==old_pin:
  #       print("New pin cannot be same as old pin")
  #     else:
  #       print("Pin changed successfully")
  #   else:
  #     print("Invalid pin")
  def change_pin(self):
      old_pin=input("enter your old pin")
      if old_pin==self.pin:
        new_pin=input("enter new pin")
        self.pin==new_pin
        if new_pin==old_pin:
          print("new pin cannnot be same as old pin")
        else:
          print("pin changed successfully")
      else:
        print("invalid pin")
  def check_balance(self):
    user_pin = input("Enter your pin")
    if user_pin == self.pin:
      print("Your balance is",self.balance)
    else:
      print("Invalid pin")
  def withdraw(self):
    enter_pin=input("enter pin")
    if enter_pin==self.pin:
        amount=int(input("enter the amount"))
        if amount>=self.balance:
          self.balance=self.balance-amount
          print("withdrawal sucessfully ")
        else:
          print("insufficient balance")
    else:
        print("invalid pin")
    self.menu()
obj=Atm()



